name: image

on:
  schedule:
    - cron: '0 0 * * *'

env:
  REPO: keel-hq/keel
  IMAGE: reireias/keel-arm
  GOPATH: /home/runner/work/keel-arm/keel-arm/go

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: move build files
        run: |
          mv arm.patch /tmp
          mv Dockerfile /tmp

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: install packages
        run: >
          sudo apt install -y
          gcc-arm-linux-gnueabihf

      - name: fetch github recent tag
        id: recent-tag
        run: echo "##[set-output name=tag;]$(curl -s https://api.github.com/repos/${REPO}/tags | jq -crM '.[0].name')"

      - name: fetch github recent sha
        id: recent-sha
        run: echo "##[set-output name=sha;]$(curl -s https://api.github.com/repos/${REPO}/tags | jq -crM '.[0].commit.sha')"

      - name: fetch docker tag
        id: docker-tag
        run: |
          echo "##[set-output name=tags;]$(curl -s https://registry.hub.docker.com/v2/repositories/${IMAGE}/tags/ | jq -crM '.results[].name' | tr '\n' ',')"

      - name: checkout keel-hq/keel
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO }}
          ref: ${{ steps.recent-sha.outputs.sha }}
          path: /home/runner/work/keel-arm/keel-arm/go/src/github.com/${{ env.REPO }}
        if: "!contains(steps.docker-tag.outputs.tags, steps.recent-tag.outputs.tag)"

      # image build when tag not found in docker hub
      - name: image build
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          cd ${GOPATH}/src/github.com/${{ env.REPO }}
          patch -p1 < /tmp/arm.patch
          cp /tmp/Dockerfile ./Dockerfile.armhf
          make build-arm fetch-certs
          VERSION=${{ steps.recent-tag.outputs.tag }} make armhf
        if: "!contains(steps.docker-tag.outputs.tags, steps.recent-tag.outputs.tag)"
